camera_topic: "d435/color/image_raw"
velodyne_topic: "velodyne_points"
inference_topic: "d435/color/inference_image"

mean: [0.485, 0.456 , 0.406]
std: [0.225, 0.225, 0.225]
use_cuda: False

camera_frame: "d435_color_optical_frame"

serialized_engine: "/home/yeshas/PointPainting/ros/point_painting/src/segmentation/fcn32_torchscript.pt"
json_path: "/home/yeshas/PointPainting/ros/point_painting/src/point_painting/config/color_mapping.json"