camera_topic: "d435/color/image_raw"
velodyne_topic: "velodyne_points"
inference_topic: "d435/color/inference_image"

mean: [0.485, 0.456 , 0.406]
std: [0.225, 0.225, 0.225]
# enable gpu-inference
use_cuda: False
use_server: True
server_address: "ws://10.10.2.133"
server_port: 5555

camera_frame: "d435_color_optical_frame"
costmap_size: 10.0
costmap_resolution: 0.05
inflation_radius: 0.5 

# change the below paths as required
environment: "park" # park or office
serialized_engine: "/home/yeshas/PointPainting/point_painting/src/point_painting/assets/fcn32_torchscript.pt"
json_path: "/home/yeshas/PointPainting/point_painting/src/point_painting/config/color_mapping.json"
